### ISSUE TITLE
New hotkey not allowed?

### ISSUE THREAD

**Issue by andershoejlund** [jmmerz/move-tab-hotkeys#17]
Hi,
Thank you for a great add-on.
My question is why am I not allowed to set the custom hot key `ctrl + alt + cmd + (left) or (rigth)`?
Thank you. Anders

**Comment by jmmerz** [comment]
Hi @andershoejlund, I'm glad you find move-tab-hotkeys useful!

I'm assuming you're on a Mac due to the `cmd` key, and I'm guessing that you use the add-on in Firefox since it sounds like you're likely using the built-in hotkey configuration.

I wrote the custom hotkey options to support changing keys when Firefox didn't yet support a UI for setting hotkeys natively. I have a vague recollection that certain key combinations were not mappable on the Mac I was using at the time, but that may very well have changed. Right now I unfortunately don't have easy access to a Mac to test with.

Modern versions of Firefox have added the ability to set hot keys natively and I'm hoping that will do the job. Can you try:
1. Open the Add-ons page:
![image](https://user-images.githubusercontent.com/1848149/104354551-3682e700-54be-11eb-8967-cd903b3c8fbd.png)

2. From there, open the **Manage Extension Shortcuts** page:
![image](https://user-images.githubusercontent.com/1848149/104354979-dcceec80-54be-11eb-8431-a7820f9422a7.png)

3. On that page, there should be an entry for Move-Tab-Hotkeys where you can set keys using Firefox's native capabilities. That should either let you set the key or else might give you a more specific message regarding what interferes with it.
![image](https://user-images.githubusercontent.com/1848149/104355248-3f27ed00-54bf-11eb-8c64-f1a23845bd91.png)

If that does work, can you please let me know? I'm not certain what the built-in hotkey options will do if you set a key they wouldn't allow from the native configuration, so it might be time for me to remove those options in favor of Firefox's regular tool.

**Comment by jmmerz** [comment]
Ahh, apologies - I just re-read the Firefox documentation and I think my suggestion above will not work. Referencing the [Web Extensions Key Combinations](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#key_combinations) text it appears that Firefox allows at most two modifier keys for hot keys for add-ons. If that's true there's probably no solution for it.

**Comment by andershoejlund** [comment]
@jmmerz thank you so much!

I did not know about that firefox option. I made another custom hotkey and everything is working perfectly.

Incredible.
