### ISSUE TITLE
ALT+ SHIFT + 0/9 : numeric keypad is not working, only the number above the letters

### ISSUE THREAD

**Issue by syldub69** [jmmerz/move-tab-hotkeys#5]
I use a standard keyboard.
<kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>0</kbd> or <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>9</kbd> shortkeys are only working if I use the number keys above the letters (the numeric keypad is not working).
Could you fix it?

What is curious (but nice!) is that <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>0</kbd> or <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>9</kbd> is working with keys above the letters even if <kbd>CAPS LOCK</kbd> is ON or OFF (on the French keyboard: 0 = à and 9 = ç)

**Comment by jmmerz** [comment]
Thanks for reporting this! I must confess I hadn't tested with the number pad.

I think I see how to fix it. I will try to get an updated version published with a fix this evening after I get home (which will be 10-12 hours from now for me).

If you strictly prefer the numeric keypad over the numbers in the top row _and_ if you're using Chrome, there's a partial workaround you could use: You can manually adjust the shortcut in Chrome, though it would mean you could use the number pad but not the numbers in the top row of the keyboard. If you wish to try it, you can use the instructions in [this LifeHacker article](https://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121) and entering Alt+Shift+[Numpad 0] and Alt+Shift+[Numpad 9]. Those will translate into Chrome as Alt+Shift+Ins and Alt+Shift+PageUp if you have the Number Lock turned off, or the same but without the Shift (even if you press it) if Num Lock is on. Unfortunately that means that to actually use the shortcut, your Num Lock needs to be in the same on/off state it was in when you set the shortcut. I'll attempt to address that as well so that the state of Num Lock doesn't matter.

If you're using Firefox, Firefox doesn't support adding your own shortcuts yet, so you'll need to wait for my update.

Otherwise if my plan for the new version works out, it should support both the numbers row and the number pad, with Num Lock either on or off.

**Comment by jmmerz** [comment]
@syldub69 Thanks again for the report. I've got a fix I've tested in Firefox (not released yet), but Chrome unfortunately allows only a maximum of four shortcut keys per extension. Since the number pad keys register as different keys from the numbers in the top row in the browser, the only way I see so far to make it work is to add additional shortcut keys to support the number pad, and it takes a total of 4 more in addition to the original 4 in order to support it with NumLock turned both on and off.

I'm going to do a bit more research and see if I can find a way to do it. One thought is to add a separate version of the Chrome extension that supports moving the tab to first/last position using the number pad, though that seems a bit hacky. An alternate workaround is still as I described in [my comment above](https://github.com/jmmerz/move-tab-hotkeys/issues/5#issuecomment-369340516), though that's not really ideal either since it takes away the top row number keys.

I'll update the comments here as I progress.

**Comment by syldub69** [comment]
Thanks for your work!

**Comment by jmmerz** [comment]
Hi @syldub69, thanks again for the original problem report and for your patience while I didn't get back to working on this for several weeks.

I haven't been able to find any way to force a Chrome extension to allow more than 4 keyboard shortcuts, so I ended up releasing a second variant of the extension for Chrome to support the additional keys necessary for using both the number row at the top of the keyboard and the number pad.

The final resolution is:
* For Firefox, released a new version (1.2.0 or later) that supports both the number row and number pad for moving tabs to first/last position in the tab bar.
* For Chrome, released a second variant ("Move Tab Hotkeys (Chrome Number Pad Keys)") that supports additional shortcuts for using the number pad in addition to the number keys at the top of the keyboard.

**Comment by syldub69** [comment]
Thanks a lot!
